In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [3]:

df = pd.read_csv('../dataset/subride_clean_under.csv')

kolom_target = 'review' 

# Jika ada baris kosong
df[kolom_target] = df[kolom_target].fillna('')

In [4]:

# Ubah kolom DataFrame kembali menjadi format list yang dipahami TfidfVectorizer
dokumen = df[kolom_target].tolist()

In [5]:

dokumen[:5]

['gojek makin kesini makin gjls segitu banyak nya gojek di dekat stasiun tidak ada yang mengambil sama sekali posisi saya lagi mau kerja buru buru lebih baik ojek pangkalan meskipun mahal yang penting sat set',
 'mohon penjelasan nya an nusron driver b 1961 rop kenapa tarif nya rp 97500 jadi rp 107000 berangkat sedangkan balik pulang tarifnya sesuai rp 99500 driver z 1517 em an wahyu hidayat oke',
 'kepada yth maxim mohon mohon banget ongkosnya di naikkan lagi kalau cuaca sedang hujan apalagi kalau sedang hujan deras kasihan banget sama driver nya',
 'bingung deh soal algoritma program ini paramernya bagaimana ya seharusnya jika tidak mendapatkan driver sesuai dengan tenggat waktu harusnya batal lah kalau sampai menunggu sampai dapat driver nunggunya kelamaan',
 'ini tolong benar kacau selalu kacaunya apalagi gocar kalau memang lagi nganter penumpang driver nya itu tidak usah ambil penumpang dulu coy tolong lah lama kami menunggu tolong di perbaiki lagi']

In [6]:

# Inisialisasi model TF-IDF
vectorizer = TfidfVectorizer(lowercase=True)

In [7]:


# Fit dan Transform
tfidf_matrix = vectorizer.fit_transform(dokumen)

In [8]:

tfidf_matrix = vectorizer.fit_transform(dokumen)

import joblib

joblib.dump(
    vectorizer,
    'tfidf_vectorizer_norm1.pkl'
)

print("Vectorizer berhasil disimpan")

Vectorizer berhasil disimpan

In [9]:

# sebagai kolom
kata_kunci = vectorizer.get_feature_names_out()

In [10]:

print(f"Total kata unik (fitur) yang berhasil diekstrak: {len(kata_kunci)} kata")
print("=== Sampel 15 Kata Pertama ===")
print(kata_kunci[:15])

print("\n=== Sampel 15 Kata Terakhir ===")
print(kata_kunci[-15:])

Total kata unik (fitur) yang berhasil diekstrak: 3331 kata
=== Sampel 15 Kata Pertama ===
['0312' '0530' '10' '100' '10000' '1000000' '1015' '10200' '10400' '1049'
 '107000' '110' '11000' '115' '12']

=== Sampel 15 Kata Terakhir ===
['yaudah' 'ydh' 'yemakacih' 'yesus' 'yng' 'yo' 'yq' 'yth' 'yuk' 'yutub'
 'ywd' 'zaini' 'zaman' 'zoom' 'zoomin']

In [11]:


# Ubah hasil TF-IDF menjadi DataFrame
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=kata_kunci)

In [12]:


print(f"Ukuran Dataset TF-IDF: {df_tfidf.shape[0]} baris dokumen x {df_tfidf.shape[1]} kolom kata\n")

print("=== Matriks Bobot TF-IDF (5 Baris Pertama) ===")
display(df_tfidf.head(5))

print("=== Matriks Bobot TF-IDF (5 Baris Tengah) ===")
display(df_tfidf.iloc[96:101])

print("=== Matriks Bobot TF-IDF (5 Baris Terakhir) ===")
display(df_tfidf.tail(5))

Ukuran Dataset TF-IDF: 756 baris dokumen x 3331 kolom kata

=== Matriks Bobot TF-IDF (5 Baris Pertama) ===

,0312,0530,10,100,10000,1000000,1015,10200,10400,1049,...,yo,yq,yth,yuk,yutub,ywd,zaini,zaman,zoom,zoomin
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.268024,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

=== Matriks Bobot TF-IDF (5 Baris Tengah) ===

,0312,0530,10,100,10000,1000000,1015,10200,10400,1049,...,yo,yq,yth,yuk,yutub,ywd,zaini,zaman,zoom,zoomin
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

=== Matriks Bobot TF-IDF (5 Baris Terakhir) ===

,0312,0530,10,100,10000,1000000,1015,10200,10400,1049,...,yo,yq,yth,yuk,yutub,ywd,zaini,zaman,zoom,zoomin
751,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
752,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
753,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
754,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
df_tfidf['label'] = df['label']

df_tfidf.to_csv(
    '../dataset/tfidf_norm1.csv',
    index=False
)

print("Berhasil disimpan ke ../dataset/tfidf_norm1.csv")

Berhasil disimpan ke ../dataset/tfidf_norm1.csv