In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("undersampling_result.csv")

In [12]:
df.info()
df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 604 entries, 0 to 603
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  604 non-null    int64
 1   review      604 non-null    str
 2   label       604 non-null    int64
dtypes: int64(2), str(1)
memory usage: 14.3 KB

   Unnamed: 0                                             review  label
0           0  tolang pelanggan terrsayang mohon diperhatikan...      1
1           1  keamanan kenyamanan konsumen perhatikan bnyk a...      0
2           2  buset nungguin pesenan gacoan jam 1049 sampe j...      0
3           3  terimakasih gercep ramah baru pertama kali mak...      1
4           4  aplikasi boncos tarif minimum menyentuh 10200 ...      1

In [2]:
import indo_normalizer
from indo_normalizer import Normalizer

In [3]:
normalizer = Normalizer()

Korpus 'c:\mine-pro\pkb-ride\.venv\Lib\site-packages\indo_normalizer\corpus\common_words.txt' berhasil dimuat. (18122 kata)
Korpus 'c:\mine-pro\pkb-ride\.venv\Lib\site-packages\indo_normalizer\corpus\slangs.csv' berhasil dimuat. (1284 pasangan)

In [5]:
def indo_normalize(text):
    normalized_text, _ = normalizer.normalize_text(str(text))
    return normalized_text

In [13]:
df['review'] = df['review'].apply(indo_normalize)

In [14]:
df

     Unnamed: 0                                             review  label
0             0  orang pelanggan terbayang mohon diperhatikanla...      1
1             1  keamanan kenyamanan konsumen perhatikan bnyk a...      0
2             2  buset menunggu pesenan gacoan jam soal sampai ...      0
3             3  terimakasih gercep ramah baru pertama kali mem...      1
4             4  aplikasi boncos tarif minimum menyentuh zoo la...      1
..          ...                                                ...    ...
599         599  gila grab lama lama resep grabcar lama banget ...      1
600         600  aku harap penumpang melihat rating gojek bukan...      1
601         601  pelayanan mohon perbaikijangan biar kan pelang...      1
602         602  info management maxim driver pakai aplikasi ma...      0
603         603  mengira cuman saja ternyata banyak komplain di...      1

[604 rows x 3 columns]

In [15]:
df_original = pd.read_csv("undersampling_result.csv")

In [ ]:
df_original['review_normal'] = df_original['review_normal']

hasil, perubahan = normalizer.normalize_text(sample)

print("ASLI:")
print(sample)

print("\nHASIL:")
print(hasil)

print("\nPERUBAHAN:")
print(perubahan)

KeyError: 'review_normal'