In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [3]:

df = pd.read_csv('no_stem_reviews.csv')

kolom_target = 'review' 

# Jika ada baris kosong
df[kolom_target] = df[kolom_target].fillna('')

In [4]:

# Ubah kolom DataFrame kembali menjadi format list yang dipahami TfidfVectorizer
dokumen = df[kolom_target].tolist()

In [5]:

dokumen[:5]

['semoga kedepan talangan g susah dapat karna jualan pakai jasa maxim perlu talangan lama banget kalau cari driver mau talangan',
 'buat pusat grab perbaiki jangan dikit tangguhkan buat driver jngn gampang melaporkan krna laporan km menghilangkan rezeki driver lain',
 'woi gojek kalo mau bikin verifikasi minimal depan belakang lah kamera depan doang apa si dulu tidak pakai verifikasi muka sekarang jadi pakai mau bikin protect driver jual beli account kocak lu gojek',
 'aplikasi sangat baik bikin jelek drive cara bicara tidak sopan tidak pantas dengaringin rasa berhenti gunakan apalikasi initapi tidak semua driver gituini beberapa driver',
 'maxsim bagus sayang nya nga fitur telpon buat driver sama buat poto kalau gojek buat amit maxsim biar telpon donk']

In [6]:

# Inisialisasi model TF-IDF
vectorizer = TfidfVectorizer(lowercase=False)

In [7]:


# Fit dan Transform
tfidf_matrix = vectorizer.fit_transform(dokumen)

In [8]:

# sebagai kolom
kata_kunci = vectorizer.get_feature_names_out()

In [9]:

print(f"Total kata unik (fitur) yang berhasil diekstrak: {len(kata_kunci)} kata")
print("=== Sampel 15 Kata Pertama ===")
print(kata_kunci[:15])

print("\n=== Sampel 15 Kata Terakhir ===")
print(kata_kunci[-15:])

Total kata unik (fitur) yang berhasil diekstrak: 4835 kata
=== Sampel 15 Kata Pertama ===
['005' '0312' '05' '0530' '10' '100' '1015' '10200' '10400' '1049' '1070'
 '10k' '10menit' '10rb' '10rbu']

=== Sampel 15 Kata Terakhir ===
['yng' 'yo' 'yok' 'yos' 'you' 'yra' 'yth' 'yuk' 'yutub' 'ywd' 'zaini'
 'zakalahu' 'zaman' 'zoom' 'zoomin']

In [10]:


# Ubah hasil TF-IDF menjadi DataFrame
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=kata_kunci)

In [11]:


print(f"Ukuran Dataset TF-IDF: {df_tfidf.shape[0]} baris dokumen x {df_tfidf.shape[1]} kolom kata\n")

print("=== Matriks Bobot TF-IDF (5 Baris Pertama) ===")
display(df_tfidf.head(5))

print("=== Matriks Bobot TF-IDF (5 Baris Tengah) ===")
display(df_tfidf.iloc[96:101])

print("=== Matriks Bobot TF-IDF (5 Baris Terakhir) ===")
display(df_tfidf.tail(5))

Ukuran Dataset TF-IDF: 1338 baris dokumen x 4835 kolom kata

=== Matriks Bobot TF-IDF (5 Baris Pertama) ===

,005,0312,05,0530,10,100,1015,10200,10400,1049,...,yra,yth,yuk,yutub,ywd,zaini,zakalahu,zaman,zoom,zoomin
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

=== Matriks Bobot TF-IDF (5 Baris Tengah) ===

,005,0312,05,0530,10,100,1015,10200,10400,1049,...,yra,yth,yuk,yutub,ywd,zaini,zakalahu,zaman,zoom,zoomin
96,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.199856,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,0.0,0.0,0.0,0.0,0.279733,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

=== Matriks Bobot TF-IDF (5 Baris Terakhir) ===

,005,0312,05,0530,10,100,1015,10200,10400,1049,...,yra,yth,yuk,yutub,ywd,zaini,zakalahu,zaman,zoom,zoomin
1333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1335,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1336,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1337,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
df_tfidf['label'] = df['label']

df_tfidf.to_csv(
    'tfidf_nonstem.csv',
    index=False
)

print("Berhasil disimpan ke tfidf_nonstem.csv")

Berhasil disimpan ke tfidf_nonstem.csv