In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [23]:

df = pd.read_csv('normalisasi_satu.csv')

kolom_target = 'review' 

# Jika ada baris kosong
df[kolom_target] = df[kolom_target].fillna('')

In [24]:

# Ubah kolom DataFrame kembali menjadi format list yang dipahami TfidfVectorizer
dokumen = df[kolom_target].tolist()

In [25]:

dokumen[:5]

['orang pelanggan terbayang mohon diperhatikanlah sih abang driver iya deh pakai banyak diskon grab masa mengasih parkir z saja sepele bnget yaampun',
 'keamanan kenyamanan konsumen perhatikan bnyk akun driver memakai akun berbeda kendaraan orang datang beda data akun aplikasi orang plat nomor kendaraan beda grab sama gojek selalu sesuai maxim',
 'buset menunggu pesenan gacoan jam soal sampai jam tapi anter perkara driver tidak mau anter padahal tempat tinggal sama lokasi cuman yq menitan cok itupun disuruh menunggu yq menit buset deh',
 'terimakasih gercep ramah baru pertama kali memakai jasa gojek online enggak salah memilih maxim jadi aplikasi',
 'aplikasi boncos tarif minimum menyentuh zoo layanan pacar kau kira apaan mobil pribadi kau hargai segitu jeruk mafia banget kau aplikasi laknat']

In [26]:

# Inisialisasi model TF-IDF
vectorizer = TfidfVectorizer(lowercase=True)

In [27]:


# Fit dan Transform
tfidf_matrix = vectorizer.fit_transform(dokumen)

In [28]:

# sebagai kolom
kata_kunci = vectorizer.get_feature_names_out()

In [29]:

print(f"Total kata unik (fitur) yang berhasil diekstrak: {len(kata_kunci)} kata")
print("=== Sampel 15 Kata Pertama ===")
print(kata_kunci[:15])

print("\n=== Sampel 15 Kata Terakhir ===")
print(kata_kunci[-15:])

Total kata unik (fitur) yang berhasil diekstrak: 2369 kata
=== Sampel 15 Kata Pertama ===
['abang' 'abiss' 'abiz' 'acara' 'acc' 'aceng' 'ada' 'adek' 'adil' 'admin'
 'agama' 'agar' 'air' 'airport' 'aja']

=== Sampel 15 Kata Terakhir ===
['yaudah' 'yng' 'yoo' 'you' 'yq' 'yuk' 'yutub' 'zainudin' 'zaman' 'zest'
 'zgoizozs' 'zona' 'zonk' 'zoo' 'zoom']

In [30]:


# Ubah hasil TF-IDF menjadi DataFrame
df_tfidf = pd.DataFrame(tfidf_matrix.toarray(), columns=kata_kunci)

In [31]:


print(f"Ukuran Dataset TF-IDF: {df_tfidf.shape[0]} baris dokumen x {df_tfidf.shape[1]} kolom kata\n")

print("=== Matriks Bobot TF-IDF (5 Baris Pertama) ===")
display(df_tfidf.head(5))

print("=== Matriks Bobot TF-IDF (5 Baris Tengah) ===")
display(df_tfidf.iloc[96:101])

print("=== Matriks Bobot TF-IDF (5 Baris Terakhir) ===")
display(df_tfidf.tail(5))

Ukuran Dataset TF-IDF: 604 baris dokumen x 2369 kolom kata

=== Matriks Bobot TF-IDF (5 Baris Pertama) ===

,abang,abiss,abiz,acara,acc,aceng,ada,adek,adil,admin,...,yuk,yutub,zainudin,zaman,zest,zgoizozs,zona,zonk,zoo,zoom
0,0.239618,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
1,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.216848,0.0

=== Matriks Bobot TF-IDF (5 Baris Tengah) ===

,abang,abiss,abiz,acara,acc,aceng,ada,adek,adil,admin,...,yuk,yutub,zainudin,zaman,zest,zgoizozs,zona,zonk,zoo,zoom
96,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.404137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

=== Matriks Bobot TF-IDF (5 Baris Terakhir) ===

,abang,abiss,abiz,acara,acc,aceng,ada,adek,adil,admin,...,yuk,yutub,zainudin,zaman,zest,zgoizozs,zona,zonk,zoo,zoom
599,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
600,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
602,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
603,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0